security:

    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            entry_point: App\Security\UserAuthenticator
            custom_authenticator: App\Security\UserAuthenticator
            lazy: true
            provider: app_user_provider
            #http_basic: true

            logout:
                path: app.logout
                target: app.index

            form_login:
                check_path: app.login
                login_path: app.login
                enable_csrf: true

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 1209600

    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/teacher/create, roles: [ROLE_ADMIN] }
        - { path: ^/teacher/\d+/update, roles: [ROLE_ADMIN] }
        - { path: ^/teacher/\d+/delete, roles: [ROLE_ADMIN] }
        - { path: ^/teacher/\d+, roles: [ROLE_ADMIN, ROLE_USER] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10